### ISSUE TITLE
Xiaomi Poco F2 Pro

### ISSUE THREAD

**Issue by MasterSokin** [lapwat/NfcScreenOffPie#1]
The module doesn't work with Xiaomi Poco F2 Pro running xiaomi.eu rom 12.0.8. Can't enable NFC at all after restart.

**Comment by lapwat** [comment]
You need to provide more information for me to handle this issue (logs, steps to reproduce, ...).

You might consider installing this module https://forum.xda-developers.com/t/module-nfc-screen-off.4034903/ available in Magisk.
